version: "3.3"

services:
  api:
    container_name: express_api
    restart: unless-stopped
    image: express-api:1.0.0
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - shared-network

  client:
    container_name: react_api
    restart: unless-stopped
    image: react-client:1.0.0
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - 80:3000
    networks:
      - shared-network
    depends_on:
      - api

networks:
  shared-network:
