version: "3.3"

services:
  react-app:
    image: react-app
    stdin_open: true
    ports:
      - "80:3000"
    networks:
      - shared-network
    build:
      context: client
      dockerfile: Dockerfile

  api-server:
    image: api-server
    ports:
      - "3001:3001"
    networks:
      - shared-network
    build:
      context: server
      dockerfile: Dockerfile

networks:
  shared-network:
    driver: bridge
